platform :ios, '9.0'

target ‘B&P Messenger’ do
use_frameworks!

pod 'Firebase/Core'
pod 'Firebase/Storage'
pod 'Firebase/Auth'
pod 'Firebase/Database'
pod 'Toast-Swift', '~> 2.0.0'
pod 'Atlas'


end
